version: "3.8"

services:
  backend:
    environment:
      - ENV_VAR_KEY=value
    build: ./backend/
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
